# Prefacio {.unnumbered}

Este documento no pretende ser un manual detallado sobre el desarrollo de un juego de RPG de acción. Lo que sí pretende es ser un conjunto de apuntes que registre el proceso seguido para armar uno de estos juegos, en un nivel básico. Cabe decir que se requiere cierto conocimiento del motor y de su interfaz. Y si se tiene un poco de experiencia realizando juegos más sencillos, mucho mejor. Recomiendo echar un vistazo al libro Apuntes del Desarrollo de Videojuegos en Godot, que se encuentra en el mismo lugar donde se encontró este.

El desarrollo de videojuegos no es fácil, pero puede aligerarse un poco si se documenta cada paso exitoso y, ¿por qué no? también los errores. Lo que me lleva a otro punto: el idioma. Y no me refiero al que utiliza Godot, que es muy bueno. Me refiero al uso prioritario del español en este documento. Trato de utilizar nombres de archivos, carpetas, variables e incluso funciones en español para facilitar, si cabe decirlo, un poco más el aprendizaje. No sumemos más dificultades a la programación.

En cuanto al motor Godot pues, escribir un libro sobre cualquier paquete informático puede complicarse bastante si este es de naturaleza abierta (*open source*), ya que normalmente evolucionan y cambian mucho conforme pasa el tiempo. Sin embargo, la idea es mantenerlo actualizado, que evolucione a la par. Es la única manera de pretender sostener su razón de ser. Y sí, este librito lo estuve escribiendo al mismo tiempo que el de los Metroidvania, así que varias cosas serán recicladas de allá, nada grave, supongo. Dicho lo dicho, al grano. Vamos por ese RPG.
